# Default values for argo-test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

paths:
  client: /?(.*)
  api: /api/?(.*)

ports:
  client: 3000
  server: 5000
  postgres: 5432
